# Generated by Django 2.1.1 on 2018-09-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added',
            field=models.ManyToManyField(related_name='added_products', to='app.User'),
        ),
    ]
